package com.example.terrabit_app.utils

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import com.example.terrabit_app.R
import kotlin.String


class ElementosConCodigos {
    @Composable
    fun sexos(): Map<String, String>{
        val tipos = mapOf<String, String>(
            "02" to stringResource(R.string.male),
            "01" to stringResource(R.string.female)
        )
        return tipos
    }

    @Composable
    fun aptitudes(): Map<String, String> {
        val aptitudes = mapOf<String, String>(
            "02" to stringResource(R.string.option_aptitude_meat),
            "01" to stringResource(R.string.option_aptitude_milk),
            "03" to stringResource(R.string.option_aptitude_double)
        )
        return aptitudes
    }
    @Composable
    fun muertes(): Map<String, String>{
        val listaTiposMuerte = mapOf<String, String>(
            stringResource(R.string.form_type_dead_dead) to "01",
            stringResource(R.string.form_type_dead_abort) to "02"
        )
        return listaTiposMuerte
    }

    @Composable
    fun transporte(): Map<String, String> {
        val listaTransporte = mapOf<String, String>(
            "04" to stringResource(R.string.option_truck),
            "05" to stringResource(R.string.option_boat),
            "06" to stringResource(R.string.option_airplane),
            "07" to stringResource(R.string.option_train),
            "08" to stringResource(R.string.option_walking),
            "99" to stringResource(R.string.option_other)
        )
        return listaTransporte
    }

    @Composable
    fun estadosLlegada(): Map<String, String> {
        val listaEstadosLlegada = mapOf<String, String>(
            "92" to stringResource(R.string.option_arrival),
            "93" to stringResource(R.string.option_death_transport),
            "94" to stringResource(R.string.option_death_stable),
            "80" to stringResource(R.string.option_sacrificed)
        )
        return listaEstadosLlegada
    }

    @Composable
    fun opcionesSiNo(): Map<String, String>{
        val listaOpciones= mapOf<String, String>(
             "SI" to stringResource(R.string.option_yes) ,
             "NO" to stringResource(R.string.option_no)
        )
        return listaOpciones
    }

    @Composable
    fun tiposPresentacion(): Map<String, String>{
        val listaTiposPresentacion = mapOf<String, String>(
            "1" to "I",
            "2" to "IIA",
            "3" to "IIB",
            "4" to "IIIA",
            "5" to "IIIB"
        )
        return listaTiposPresentacion

    }

    @Composable
    fun tiposEnvios() : Map<String, String> {
        val listaTiposEnvios = mapOf<String, String>(
            "01" to stringResource(R.string.option_ordinary_mail),
            "04" to stringResource(R.string.option_certificate_mail)
        )
        return listaTiposEnvios
    }

    @Composable
    fun tiposDireccionEnvio(): Map<String, String>{
        val listaTiposDireccionEnvio = mapOf<String, String>(
            "01" to "OC",
            "02" to stringResource(R.string.option_rancher),
            "03" to stringResource(R.string.option_alternative_address)
        )
        return  listaTiposDireccionEnvio
    }

    @Composable
    fun tiposMaterialDuplicados(): Map<String, String>{
        val listaTiposMaterial = mapOf<String, String>(
            "07" to stringResource(R.string.option_crotal),
            "20" to stringResource(R.string.option_electronic_crotal),
            "21" to stringResource(R.string.option_electronic_injectable),
            "22" to stringResource(R.string.option_ruminal_bowl)
        )
        return listaTiposMaterial
    }
    @Composable
    fun tiposMaterial(): Map<String, String>{
        val listaTiposMaterial = mapOf<String, String>(
            "21" to stringResource(R.string.option_electronic_injectable),
            "22" to stringResource(R.string.option_ruminal_bowl),
            "23" to stringResource(R.string.option_crotal_simple_tisular),
            "24" to stringResource(R.string.option_crotal_double_tisular),
            "26" to stringResource(R.string.option_crotal_electronic_crotal),
            "25" to stringResource(R.string.option_rebuilding)
        )
        return listaTiposMaterial
    }

    fun tiposOficinasComarcales(): Map<String, String> {
        val listaOc = mapOf<String, String>(
            "OC001" to "Alt Camp",
            "OC002" to "Alt Empordà",
            "OC003" to "Alt Penedès",
            "OC004" to "Alt Urgell",
            "OC005" to "Alta Ribagorça",
            "OC006" to "Anoia",
            "OC007" to "Bages",
            "OC008" to "Baix Camp",
            "OC009" to "Baix Ebre",
            "OC010" to "Baix Empordà",
            "OC011" to "Baix Llobregat",
            "OC012" to "Baix Penedès",
            "OC013" to "Barcelonès",
            "OC014" to "Berguedà",
            "OC015" to "Cerdanya",
            "OC016" to "Conca de Barberà",
            "OC017" to "Garraf",
            "OC018" to "Garrigues",
            "OC019" to "Garrotxa",
            "OC020" to "Gironès",
            "OC021" to "Maresme",
            "OC022" to "Montsià",
            "OC023" to "Noguera",
            "OC024" to "Osona",
            "OC025" to "Pallars Jussà",
            "OC026" to "Pallars Sobirà",
            "OC027" to "Pla d'Urgell",
            "OC028" to "Pla de l'Estany",
            "OC029" to "Priorat",
            "OC030" to "Ribera d'Ebre",
            "OC031" to "Ripollès",
            "OC032" to "Segarra",
            "OC033" to "Segrià",
            "OC034" to "La Selva",
            "OC035" to "Solsonès",
            "OC036" to "Tarragonès",
            "OC037" to "Terra Alta",
            "OC038" to "Urgell",
            "OC039" to "Vall d'Aran",
            "OC040" to "Vallès Occidental",
            "OC041" to "Vallès Oriental",
            "OC042" to "Moianès"
        )
        return listaOc
    }


    fun tipoEmpresaSubministradora(): Map<String, String>{
        val listaEmpresas = mapOf<String, String>(
            "B02164317" to "DATAMARS IBERICA SLU",
            "A78100609" to "AZASA"
        )
        return  listaEmpresas
    }

    fun razasBovinas(): Map<String, String> {
        val listaRazas = mapOf(
            "9999" to "Otras",
            "0000" to "Conjunto Mestizo",
            "0099" to "Desconocida",
            "0201" to "Abondance",
            "1101" to "Albera",
            "1164" to "Alentejana",
            "1102" to "Alistana-Sanabresa",
            "0801" to "Angler",
            "1116" to "Angus",
            "1166" to "Arouquesa",
            "0202" to "Armoricaine",
            "1103" to "Asturiana de la Montaña",
            "1125" to "Asturiana de los Valles",
            "1151" to "Ayrshire",
            "0203" to "Aurochs Reconstitue",
            "1121" to "Avileña-Negra Ibérica",
            "0802" to "Aubrac",
            "1160" to "Baltata Romanesca",
            "0204" to "Bazadaise",
            "0205" to "Bearnaise",
            "1104" to "Betizu",
            "1137" to "Berrenda Colorada",
            "1132" to "Berrenda Negra",
            "9901" to "Bisonte",
            "1141" to "Blanca Belga",
            "1124" to "Blanca Cacereña",
            "0206" to "Blue du Nord",
            "0207" to "Bordelaise",
            "9902" to "Brahman",
            "0208" to "Brettonne Pie Noire",
            "1105" to "Bruna de los Pirineos",
            "1152" to "Búfalo",
            "1131" to "Cárdena Andaluza",
            "1144" to "Cachena",
            "1145" to "Caldelana",
            "1134" to "Canaria",
            "0225" to "Camargue",
            "0209" to "Casta (Aure y St. Girons)",
            "9903" to "Cebú",
            "1153" to "Chianina",
            "1113" to "Charolesa",
            "0210" to "Coopelso",
            "0211" to "Corse",
            "0212" to "Creole",
            "0803" to "Dexter",
            "0213" to "Ferrandaise",
            "1130" to "Fleckvieh",
            "0214" to "Froment du Leon",
            "1111" to "Frisona",
            "1146" to "Frieiresa",
            "0804" to "Galloway",
            "1156" to "Gasconne",
            "0215" to "Gelbvieh",
            "1154" to "Guernsey",
            "0805" to "Highland",
            "0216" to "Herens",
            "1114" to "Hereford",
            "0217" to "Inra",
            "0806" to "Irish Maol / Droimeann",
            "1115" to "Jersey",
            "0807" to "Kerry",
            "0233" to "Kobe",
            "1140" to "Lidia",
            "1147" to "Limiana",
            "1117" to "Limusina",
            "0218" to "Lourdaise",
            "1107" to "Mallorquina",
            "0220" to "Marchigiana",
            "0219" to "Maraichine",
            "1109" to "Marismeña",
            "0808" to "Maine Anjou-Rouge des Prés",
            "1136" to "Menorquina",
            "1159" to "Mertolenga",
            "0221" to "Mirandaise",
            "1108" to "Monchina",
            "1155" to "Montbeliard",
            "1123" to "Morucha",
            "1162" to "Pasiega",
            "1126" to "MRY",
            "1157" to "Murciana-Levantina",
            "0809" to "Murray Grey",
            "0222" to "N. Dama",
            "1138" to "Negra Andaluza",
            "0223" to "Nantaise",
            "1127" to "Normanda",
            "1167" to "Norueguesa",
            "1139" to "Pajuna",
            "1168" to "Pallaresa",
            "1158" to "Parda de Montaña",
            "1112" to "Parda",
            "0810" to "Partenaise",
            "0224" to "Pie Rouge des Plaines",
            "1143" to "Piamontesa",
            "1129" to "Pirenaica",
            "1135" to "Palmera",
            "9908" to "Pinzgauer",
            "1169" to "Preta",
            "1171" to "Ramo Grande",
            "1120" to "Retinta",
            "1122" to "Rubia Gallega",
            "1142" to "Rubia de Aquitania",
            "0226" to "Rouge Flamande",
            "0811" to "Romagnola",
            "0812" to "Rotbunte",
            "1161" to "Roja Letona",
            "1118" to "Roja Danesa",
            "0813" to "Salers",
            "1149" to "Sayaguesa",
            "0227" to "Saosnoise",
            "1163" to "Serrana de Teruel",
            "1110" to "Serrana Negra",
            "9906" to "Shorthorn",
            "9907" to "Simmental",
            "0814" to "South Devon",
            "1165" to "Swedish Red and White",
            "1119" to "St. Gertrudis",
            "0228" to "Tarentaise",
            "1150" to "Terreña",
            "1158" to "Parda de Montaña",
            "1128" to "Tudanca",
            "1170" to "Valdostana",
            "1148" to "Vianesa",
            "0229" to "Villard de Lans",
            "0230" to "Vosgienne",
            "0231" to "Wagyu",
            "0232" to "Watusi"
        )
        return listaRazas
    }

    fun getRazaBovinas(codigo: String): String {
        val listaRazas = mapOf(
            "9999" to "Otras",
            "0000" to "Conjunto Mestizo",
            "0099" to "Desconocida",
            "0201" to "Abondance",
            "1101" to "Albera",
            "1164" to "Alentejana",
            "1102" to "Alistana-Sanabresa",
            "0801" to "Angler",
            "1116" to "Angus",
            "1166" to "Arouquesa",
            "0202" to "Armoricaine",
            "1103" to "Asturiana de la Montaña",
            "1125" to "Asturiana de los Valles",
            "1151" to "Ayrshire",
            "0203" to "Aurochs Reconstitue",
            "1121" to "Avileña-Negra Ibérica",
            "0802" to "Aubrac",
            "1160" to "Baltata Romanesca",
            "0204" to "Bazadaise",
            "0205" to "Bearnaise",
            "1104" to "Betizu",
            "1137" to "Berrenda Colorada",
            "1132" to "Berrenda Negra",
            "9901" to "Bisonte",
            "1141" to "Blanca Belga",
            "1124" to "Blanca Cacereña",
            "0206" to "Blue du Nord",
            "0207" to "Bordelaise",
            "9902" to "Brahman",
            "0208" to "Brettonne Pie Noire",
            "1105" to "Bruna de los Pirineos",
            "1152" to "Búfalo",
            "1131" to "Cárdena Andaluza",
            "1144" to "Cachena",
            "1145" to "Caldelana",
            "1134" to "Canaria",
            "0225" to "Camargue",
            "0209" to "Casta (Aure y St. Girons)",
            "9903" to "Cebú",
            "1153" to "Chianina",
            "1113" to "Charolesa",
            "0210" to "Coopelso",
            "0211" to "Corse",
            "0212" to "Creole",
            "0803" to "Dexter",
            "0213" to "Ferrandaise",
            "1130" to "Fleckvieh",
            "0214" to "Froment du Leon",
            "1111" to "Frisona",
            "1146" to "Frieiresa",
            "0804" to "Galloway",
            "1156" to "Gasconne",
            "0215" to "Gelbvieh",
            "1154" to "Guernsey",
            "0805" to "Highland",
            "0216" to "Herens",
            "1114" to "Hereford",
            "0217" to "Inra",
            "0806" to "Irish Maol / Droimeann",
            "1115" to "Jersey",
            "0807" to "Kerry",
            "0233" to "Kobe",
            "1140" to "Lidia",
            "1147" to "Limiana",
            "1117" to "Limusina",
            "0218" to "Lourdaise",
            "1107" to "Mallorquina",
            "0220" to "Marchigiana",
            "0219" to "Maraichine",
            "1109" to "Marismeña",
            "0808" to "Maine Anjou-Rouge des Prés",
            "1136" to "Menorquina",
            "1159" to "Mertolenga",
            "0221" to "Mirandaise",
            "1108" to "Monchina",
            "1155" to "Montbeliard",
            "1123" to "Morucha",
            "1162" to "Pasiega",
            "1126" to "MRY",
            "1157" to "Murciana-Levantina",
            "0809" to "Murray Grey",
            "0222" to "N. Dama",
            "1138" to "Negra Andaluza",
            "0223" to "Nantaise",
            "1127" to "Normanda",
            "1167" to "Norueguesa",
            "1139" to "Pajuna",
            "1168" to "Pallaresa",
            "1158" to "Parda de Montaña",
            "1112" to "Parda",
            "0810" to "Partenaise",
            "0224" to "Pie Rouge des Plaines",
            "1143" to "Piamontesa",
            "1129" to "Pirenaica",
            "1135" to "Palmera",
            "9908" to "Pinzgauer",
            "1169" to "Preta",
            "1171" to "Ramo Grande",
            "1120" to "Retinta",
            "1122" to "Rubia Gallega",
            "1142" to "Rubia de Aquitania",
            "0226" to "Rouge Flamande",
            "0811" to "Romagnola",
            "0812" to "Rotbunte",
            "1161" to "Roja Letona",
            "1118" to "Roja Danesa",
            "0813" to "Salers",
            "1149" to "Sayaguesa",
            "0227" to "Saosnoise",
            "1163" to "Serrana de Teruel",
            "1110" to "Serrana Negra",
            "9906" to "Shorthorn",
            "9907" to "Simmental",
            "0814" to "South Devon",
            "1165" to "Swedish Red and White",
            "1119" to "St. Gertrudis",
            "0228" to "Tarentaise",
            "1150" to "Terreña",
            "1158" to "Parda de Montaña",
            "1128" to "Tudanca",
            "1170" to "Valdostana",
            "1148" to "Vianesa",
            "0229" to "Villard de Lans",
            "0230" to "Vosgienne",
            "0231" to "Wagyu",
            "0232" to "Watusi"
        )
        return listaRazas[codigo] ?: "Desconocida"
    }
    // Lo declaramos fuera de la función para que no se reconstruya en cada llamada (mejor rendimiento)
    private val mapaPaises = mapOf(
        "000" to "Desconegut",
        "101" to "Alemanya",
        "102" to "França",
        "103" to "Itàlia",
        "104" to "Holanda",
        "105" to "Bèlgica",
        "106" to "Luxemburg",
        "107" to "Regne Unit",
        "108" to "Irlanda",
        "109" to "Dinamarca",
        "110" to "Grècia",
        "111" to "Espanya",
        "112" to "Portugal",
        "113" to "Àustria",
        "114" to "Finlàndia",
        "115" to "Suècia",
        "201" to "Afganistan",
        "202" to "Albània",
        "203" to "Andorra",
        "204" to "Angola",
        "205" to "Antilles Holandeses",
        "206" to "Aràbia Saudita",
        "207" to "Algèria",
        "208" to "Argentina",
        "209" to "Armènia",
        "210" to "Aruba",
        "211" to "Ascensió, Illa de l'",
        "212" to "Austràlia",
        "213" to "Azerbaidjan",
        "214" to "Bahames",
        "215" to "Bahrein",
        "216" to "Bangla Desh",
        "217" to "Barbados",
        "218" to "Belize",
        "219" to "Benín",
        "220" to "Bermudes, Illes",
        "221" to "Bhutan",
        "222" to "Bielorússia",
        "223" to "Bolívia",
        "224" to "Bòsnia i Hercegovina",
        "225" to "Botswana",
        "226" to "Brasil",
        "227" to "Brunei",
        "228" to "Bulgària",
        "229" to "Burkina Faso",
        "230" to "Burundi",
        "231" to "Cap Verd",
        "232" to "Caiman, Illes",
        "233" to "Cambodja",
        "234" to "Camerun",
        "235" to "Canadà",
        "236" to "Centreafricana, República",
        "237" to "Txad",
        "238" to "Txeca, República",
        "239" to "Xile",
        "240" to "Xina",
        "241" to "Xipre",
        "242" to "Colòmbia",
        "243" to "Comores",
        "244" to "Congo",
        "245" to "Cook, Illes",
        "246" to "Corea del Nord",
        "247" to "Corea del Sud",
        "248" to "Costa d'Ivori",
        "249" to "Costa Rica",
        "251" to "Cuba",
        "252" to "Diego Garcia",
        "253" to "Dominica",
        "254" to "Dominicana, República",
        "255" to "Equador",
        "256" to "Egipte",
        "257" to "El Salvador",
        "258" to "Emirats Àrabs Units",
        "259" to "Eritrea",
        "260" to "Eslovàquia",
        "261" to "Eslovènia",
        "262" to "Estats Units",
        "263" to "Estònia",
        "264" to "Etiòpia",
        "265" to "Fèroe, Illes",
        "266" to "Fiji",
        "267" to "Filipines",
        "268" to "Gabon",
        "269" to "Gàmbia",
        "270" to "Geòrgia",
        "271" to "Ghana",
        "272" to "Granada",
        "273" to "Groenlàndia",
        "274" to "Guadalupe",
        "275" to "Guam",
        "276" to "Guatemala",
        "277" to "Guaiana Francesa",
        "278" to "Guinea Bissau",
        "279" to "Guinea Equatorial",
        "280" to "Guinea",
        "281" to "Guaiana",
        "282" to "Haití",
        "283" to "Hondures",
        "284" to "Hong Kong",
        "285" to "Hongria",
        "286" to "Índia",
        "287" to "Indonèsia",
        "288" to "Iran",
        "289" to "Iraq",
        "290" to "Islàndia",
        "291" to "Israel",
        "292" to "Jamaica",
        "293" to "Japó",
        "294" to "Jordània",
        "295" to "Kazakhstan",
        "296" to "Kenya",
        "297" to "Kirguizistan",
        "298" to "Kiribati",
        "299" to "Kuwait",
        "300" to "Laos",
        "301" to "Lesotho",
        "302" to "Letònia",
        "303" to "Líban",
        "304" to "Libèria",
        "305" to "Líbia",
        "306" to "Liechtenstein",
        "307" to "Lituània",
        "308" to "Macau",
        "309" to "Macedònia",
        "310" to "Madagascar",
        "311" to "Malàisia",
        "312" to "Malawi",
        "313" to "Maldives",
        "314" to "Mali",
        "315" to "Malta",
        "316" to "Malvines, Illes",
        "317" to "Marianes del Nord, Illes",
        "318" to "Marroc",
        "319" to "Marshall, Illes",
        "320" to "Martinica",
        "321" to "Maurici",
        "322" to "Mauritània",
        "323" to "Mayotte",
        "324" to "Mèxic",
        "325" to "Micronèsia",
        "326" to "Midway",
        "327" to "Moldàvia",
        "328" to "Mònaco",
        "329" to "Mongòlia",
        "330" to "Montserrat",
        "331" to "Moçambic",
        "332" to "Myanmar",
        "333" to "Namíbia",
        "334" to "Nauru",
        "335" to "Nepal",
        "336" to "Nicaragua",
        "337" to "Níger",
        "338" to "Nigèria",
        "339" to "Niue",
        "340" to "Noruega",
        "341" to "Nova Caledònia",
        "342" to "Nova Zelanda",
        "343" to "Oman",
        "344" to "Pakistan",
        "345" to "Palau",
        "346" to "Panamà",
        "347" to "Papua Nova Guinea",
        "348" to "Paraguai",
        "349" to "Perú",
        "350" to "Polinèsia Francesa",
        "351" to "Polònia",
        "352" to "Puerto Rico",
        "353" to "Qatar",
        "354" to "Reunion",
        "355" to "Rwanda",
        "356" to "Romania",
        "357" to "Rússia",
        "358" to "Sàhara Occidental",
        "359" to "Salomó",
        "360" to "Samoa Americana",
        "361" to "Samoa",
        "362" to "Saint Christopher i Nevis",
        "363" to "San Marino",
        "364" to "Saint Pierre i Miquelon",
        "365" to "Saint Vincent i les Grenadines",
        "366" to "Saint Helena",
        "367" to "Saint Lucia",
        "368" to "Sâo Tomé i Príncipe",
        "369" to "Senegal",
        "370" to "Seychelles",
        "371" to "Sierra Leone",
        "372" to "Singapur",
        "373" to "Síria",
        "374" to "Somàlia",
        "375" to "Sri Lanka",
        "376" to "Sud-àfrica",
        "377" to "Sudan",
        "378" to "Suïssa",
        "379" to "Surinam",
        "380" to "Swazilàndia",
        "381" to "Tadjikistan",
        "382" to "Tailàndia",
        "383" to "Taiwan",
        "384" to "Tanzània",
        "385" to "Territoris Ext. Austràlia",
        "386" to "Togo",
        "387" to "Tokelau",
        "388" to "Tonga",
        "389" to "Trinitat i Tobago",
        "390" to "Tunísia",
        "391" to "Turkmenistan",
        "392" to "Turks i Caicos, Illes",
        "393" to "Turquia",
        "394" to "Tuvalu",
        "395" to "Ucraïna",
        "396" to "Uganda",
        "397" to "Uruguai",
        "398" to "Uzbekistan",
        "399" to "Vanuatu",
        "400" to "Vaticà",
        "401" to "Veneçuela",
        "402" to "Vietnam",
        "403" to "Verge Americanes, Illes",
        "404" to "Verge Britàniques, Illes",
        "405" to "Wallis i Futuna",
        "406" to "Iemen",
        "407" to "Djibouti",
        "408" to "Sèrbia",
        "409" to "Congo, República Democràtica del",
        "410" to "Zàmbia",
        "411" to "Zimbabwe",
        "413" to "Croàcia",
        "414" to "Estat de Palestina",
        "415" to "Montenegro",
        "999" to "Altres"
    )

    fun getNombrePais(codigo: String): String {
        // Retorna el país si existe, o "Desconegut" si el código no se encuentra
        return mapaPaises[codigo] ?: "Desconegut"
    }

}